In [1]:
from bs4 import BeautifulSoup as beut
import pandas as pd
import numpy as np
import re
import requests

https://www.imdb.com/list/ls050782187/?sort=list_order%2Casc
https://www.imdb.com/list/ls050782187/?sort=list_order%2Casc&page=2

In [2]:
res ="https://www.imdb.com/list/ls050782187/?sort=list_order%2Casc"
request_header = {'Content-Type': 'text/html; charset=UTF-8','User-Agent': 'Chrome/101.0.0.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0','Accept-Encoding': 'gzip, deflate, br'}

page = requests.get(res,headers =request_header)
#page.text

In [3]:
soup=beut(page.text,'html.parser')

In [4]:
movie_name=[]
Year=[]
Duration=[]
Metascore=[]
Rating=[]
votes=[]
description=[]
director=[]
actors=[]

In [5]:
for i in soup.find_all('section',class_='ipc-page-section ipc-page-section--base ipc-page-section--sp-pageMargin list_page_mc_parent'):
    movie_name.append(re.findall('\\d+\\.\\s(.*?)\\d+h',i.text))
    Year.append(re.findall('(\\d+)\\d+h',i.text))
    Duration.append(re.findall('\\dh.*?m',i.text))
    Metascore.append(re.findall('(\\d+)Metascore',i.text))
    Rating.append(re.findall('Metascore(.*?)\\s',i.text))
    votes.append(re.findall('\\((.*?)\\)',i.text))
    description.append(re.findall('watched(.*?)\\.Director',i.text))
    director.append(re.findall('Director(.*?)Stars',i.text))
    actors.append(re.findall('Stars(.*?)\\d',i.text))

In [6]:
Name=[]
MOVIE_NAME=np.array(movie_name)
for i in MOVIE_NAME.flatten():
    Name.append(i)

In [7]:
print(Name,len(Name))

['The Godfather', 'The Silence of the Lambs', 'Star Wars: Episode V - The Empire Strikes Back', 'The Shawshank Redemption', 'The Shining', 'Casablanca', "One Flew Over the Cuckoo's Nest", 'Raiders of the Lost Ark', 'The Lord of the Rings: The Return of the King', 'Star Wars: Episode IV - A New Hope', 'The Dark Knight', 'The Godfather: Part II', 'Alien ', "Schindler's List", 'Inception', 'The Lord of the Rings: The Fellowship of the Ring', 'Alien', 'Some Like It Hot', 'Blade Runner', 'Se7en', 'Apocalypse Now', '12 Angry Men', 'The Lord of the Rings: The Two Towers', 'Terminator 2: Judgment Day', 'Star Wars: Episode VI - Return of the Jedi'] 25

In [8]:
Year_of_Release=[]
data=np.array(Year)
for i in data.flatten():
    Year_of_Release.append(i)

In [9]:
print(Year_of_Release,len(Year_of_Release))

['1972', '1991', '1980', '1994', '1980', '1942', '1975', '1981', '2003', '1977', '2008', '1974', '21986', '1993', '2010', '2001', '1979', '1959', '1982', '1995', '1979', '1957', '2002', '1991', '1983'] 25

In [10]:
Time_duration=[]
data2=np.array(Duration)
for i in data2.flatten():
    Time_duration.append(i)

In [11]:
print(Time_duration,len(Time_duration))

['2h 55m', '1h 58m', '2h 4m', '2h 22m', '2h 26m', '1h 42m', '2h 13m', '1h 55m', '3h 21m', '2h 1m', '2h 32m', '3h 22m', '2h 17m', '3h 15m', '2h 28m', '2h 58m', '1h 57m', '2h 1m', '1h 57m', '2h 7m', '2h 27m', '1h 36m', '2h 59m', '2h 17m', '2h 11m'] 25

In [12]:
Meta_Scores=[]
data2=np.array(Metascore)
for i in data2.flatten():
    Meta_Scores.append(i)

In [13]:
print(Meta_Scores,len(Meta_Scores))

['100', '86', '82', '82', '68', '100', '84', '86', '94', '90', '84', '90', '84', '95', '74', '92', '89', '98', '84', '65', '94', '97', '87', '75', '58'] 25

In [14]:
Imdb_Rating=[]
data3=np.array(Rating)
for i in data3.flatten():
    Imdb_Rating.append(i)

In [15]:
print(Imdb_Rating,len(Imdb_Rating))

['9.2', '8.6', '8.7', '9.3', '8.4', '8.5', '8.7', '8.4', '9.0', '8.6', '9.0', '9.0', '8.4', '9.0', '8.8', '8.9', '8.5', '8.2', '8.1', '8.6', '8.4', '9.0', '8.8', '8.6', '8.3'] 25

In [16]:
Imdb_votes=[]
data4=np.array(votes)
for i in data4.flatten():
    Imdb_votes.append(i)

In [17]:
print(Imdb_votes,len(Imdb_votes))

['2.1M', '1.6M', '1.4M', '3M', '1.2M', '630K', '1.1M', '1.1M', '2.1M', '1.5M', '3M', '1.4M', '807K', '1.5M', '2.7M', '2.1M', '1M', '295K', '853K', '1.9M', '741K', '923K', '1.9M', '1.2M', '1.2M'] 25

In [18]:
Movie_description=[]
data5=np.array(description)
for i in data5.flatten():
    Movie_description.append(i)

In [19]:
print(Movie_description,len(Movie_description))

['The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son', 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims', 'After the Empire overpowers the Rebel Alliance, Luke Skywalker begins training with Jedi Master Yoda, while Darth Vader and bounty hunter Boba Fett pursue his friends across the galaxy', 'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion', 'A family heads to an isolated hotel for the winter, where a sinister presence influences the father into violence. At the same time, his psychic son sees horrifying forebodings from both the past and the future', 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco', 'A newly admitted mental patient helps his docile companions defy the tyrannical head nurse', 'In 1936, archaeologists and adventurers of the U.S. government hired Indiana Jones to find the Ark of the Covenant before the Nazis could obtain its extraordinary powers', "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring", "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader", 'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness', 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate', 'Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony but finds herself battling the Alien Queen and her offspring', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron', 'After investigating a mysterious transmission of unknown origin, the crew of a commercial spacecraft encounters a deadly lifeform', 'After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in', 'A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator', 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives', 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god', 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict', "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard", 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten year old son John from an even more advanced and powerful cyborg', 'After rescuing Han Solo from Jabba the Hutt, the Rebel Alliance attempts to destroy the second Death Star while Luke struggles to help Darth Vader back from the dark side'] 25

In [20]:
Movie_director=[]
data6=np.array(director)
for i in data6.flatten():
    Movie_director.append(i)

In [21]:
print(Movie_director,len(Movie_director))

['Francis Ford Coppola', 'Jonathan Demme', 'Irvin Kershner', 'Frank Darabont', 'Stanley Kubrick', 'Michael Curtiz', 'Milos Forman', 'Steven Spielberg', 'Peter Jackson', 'George Lucas', 'Christopher Nolan', 'Francis Ford Coppola', 'James Cameron', 'Steven Spielberg', 'Christopher Nolan', 'Peter Jackson', 'Ridley Scott', 'Billy Wilder', 'Ridley Scott', 'David Fincher', 'Francis Ford Coppola', 'Sidney Lumet', 'Peter Jackson', 'James Cameron', 'Richard Marquand'] 25

In [22]:
Movie_actors=[]
data7=np.array(actors)
for i in data7.flatten():
    Movie_actors.append(i)

In [23]:
print(Movie_actors,len(Movie_actors))

['Marlon BrandoAl PacinoJames Caan', 'Jodie FosterAnthony HopkinsScott Glenn', 'Mark HamillHarrison FordCarrie Fisher', 'Tim RobbinsMorgan FreemanBob Gunton', 'Jack NicholsonShelley DuvallDanny Lloyd', 'Humphrey BogartIngrid BergmanPaul Henreid', 'Jack NicholsonLouise FletcherMichael Berryman', 'Harrison FordKaren AllenPaul Freeman', 'Elijah WoodViggo MortensenIan McKellen', 'Mark HamillHarrison FordCarrie Fisher', 'Christian BaleHeath LedgerAaron Eckhart', 'Al PacinoRobert De NiroRobert Duvall', 'Sigourney WeaverMichael BiehnCarrie Henn', 'Liam NeesonRalph FiennesBen Kingsley', 'Leonardo DiCaprioJoseph Gordon-LevittElliot Page', 'Elijah WoodIan McKellenOrlando Bloom', 'Sigourney WeaverTom SkerrittJohn Hurt', 'Marilyn MonroeTony CurtisJack Lemmon', 'Harrison FordRutger HauerSean Young', 'Morgan FreemanBrad PittKevin Spacey', 'Martin SheenMarlon BrandoRobert Duvall', 'Henry FondaLee J. CobbMartin Balsam', 'Elijah WoodIan McKellenViggo Mortensen', 'Arnold SchwarzeneggerLinda HamiltonEdward Furlong', 'Mark HamillHarrison FordCarrie FisherPrevious'] 25

In [24]:
Movie_Data = {'Movie_name':Name,'Year_Of_Release':Year_of_Release,'Time_duration':Time_duration,
              'Meta_score':Meta_Scores,'Imdb_Rating':Imdb_Rating,
              'Imdb_votes':Imdb_votes,'Director':Movie_director,
              'Actors':Movie_actors,'Movie_Description':Movie_description}
df=pd.DataFrame(Movie_Data)

In [25]:
df.head()

,Movie_name,Year_Of_Release,Time_duration,Meta_score,Imdb_Rating,Imdb_votes,Director,Actors,Movie_Description
0,The Godfather,1972,2h 55m,100,9.2,2.1M,Francis Ford Coppola,Marlon BrandoAl PacinoJames Caan,The aging patriarch of an organized crime dyna...
1,The Silence of the Lambs,1991,1h 58m,86,8.6,1.6M,Jonathan Demme,Jodie FosterAnthony HopkinsScott Glenn,A young F.B.I. cadet must receive the help of ...
2,Star Wars: Episode V - The Empire Strikes Back,1980,2h 4m,82,8.7,1.4M,Irvin Kershner,Mark HamillHarrison FordCarrie Fisher,After the Empire overpowers the Rebel Alliance...
3,The Shawshank Redemption,1994,2h 22m,82,9.3,3M,Frank Darabont,Tim RobbinsMorgan FreemanBob Gunton,A banker convicted of uxoricide forms a friend...
4,The Shining,1980,2h 26m,68,8.4,1.2M,Stanley Kubrick,Jack NicholsonShelley DuvallDanny Lloyd,A family heads to an isolated hotel for the wi...

In [26]:
pip install selenium

Requirement already satisfied: selenium in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (4.31.0)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.2.3)
Requirement already satisfied: trio~=0.17 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from selenium) (0.29.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from selenium) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from selenium) (4.11.0)
Requirement already satisfied: websocket-client~=1.8 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from trio~=0.17->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from trio~=0.17->selenium) (3.7)
Requirement already satisfied: outcome in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from trio~=0.17->selenium) (1.17.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dhiraj rathod\anaconda3\anaconda\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Note: you may need to restart the kernel to use updated packages.

In [27]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

url = "https://www.imdb.com/list/ls050782187/?sort=list_order,asc"

driver = webdriver.Chrome()
driver.get(url)

# Scroll to load all movies
last_height = driver.execute_script("return document.body.scrollHeight")
while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2)  # Wait for loading
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

# Extract all movies
Movie_name=[]
Year=[]
Time=[]
metascore=[]
Rating=[]
Imdb_votes=[]
Movie_description=[]
director=[]
actors=[]
genre=[]
soup = beut(driver.page_source, "html.parser")
for movie in soup.find_all("h3", class_="ipc-title__text"):
      Movie_name.append(movie.text)
for movie in soup.find_all("span", class_="sc-5179a348-7 idrYgr dli-title-metadata-item"):
    regex=re.findall('\\d{4}',movie.text)
    if regex:
        Year.append(regex[0])
    regex2=re.findall('\\dh\\s\\d+m|\\dh',movie.text)
    if regex2:
        Time.append(regex2[0])
    data = re.findall('m\\s(.*?)\\s\\d{4}|h\\s(.*?)\\s\\d{4}|m\\s(\\w+)',movie.text)
    if data:
        Type.append(data[0])

for movie in soup.find_all("span", class_="sc-ae9e80c5-0 gXcoKx metacritic-score-box"):
        metascore.append(movie.text)

for movie in soup.find_all('span',class_='ipc-rating-star--rating'):
    Rating.append(movie.text)

for movie in soup.find_all("span", class_="ipc-rating-star--voteCount"):
    regex=re.findall('\\((.*?)\\)',movie.text)
    if regex:
        Imdb_votes.append(regex[0])
for movie in soup.find_all("div", class_="ipc-html-content-inner-div"):
    Movie_description.append(movie.text)
for movie in soup.find_all('div',class_='sc-7746c29e-1 jtgnlK'):
    director.append(re.findall('Director(.*?)Stars',movie.text))
    actors.append(re.findall('Stars(.*)',movie.text))
driver.quit()

In [28]:
genre

[]

In [69]:
Name=[]
for i in range(len(Movie_name)-3):
    Name.append(Movie_name[i])
print(Name,len(Name))

['1. The Godfather', '2. The Silence of the Lambs', '3. Star Wars: Episode V - The Empire Strikes Back', '4. The Shawshank Redemption', '5. The Shining', '6. Casablanca', "7. One Flew Over the Cuckoo's Nest", '8. Raiders of the Lost Ark', '9. The Lord of the Rings: The Return of the King', '10. Star Wars: Episode IV - A New Hope', '11. The Dark Knight', '12. The Godfather Part II', '13. Aliens', "14. Schindler's List", '15. Inception', '16. The Lord of the Rings: The Fellowship of the Ring', '17. Alien', '18. Some Like It Hot', '19. Blade Runner', '20. Se7en', '21. Apocalypse Now', '22. 12 Angry Men', '23. The Lord of the Rings: The Two Towers', '24. Terminator 2: Judgment Day', '25. Star Wars: Episode VI - Return of the Jedi', '26. Die Hard', '27. Gone with the Wind', '28. Taxi Driver', '29. Pulp Fiction', '30. The Bridge on the River Kwai', '31. The Lion King', '32. North by Northwest', '33. Rear Window', '34. Léon: The Professional', '35. Back to the Future', '36. Citizen Kane', '37. Goodfellas', '38. Memento', '39. American Beauty', '40. As Good as It Gets', '41. Forrest Gump', "42. Singin' in the Rain", '43. Braveheart', '44. Saving Private Ryan', '45. Rain Man', "46. The King's Speech", '47. 2001: A Space Odyssey', '48. Kill Bill: Vol. 1', '49. Avanti!', '50. The Good, the Bad and the Ugly', '51. Amélie', '52. Modern Times', '53. Lost in Translation', '54. Full Metal Jacket', '55. Requiem for a Dream', '56. Fight Club', '57. No Country for Old Men', '58. Django Unchained', '59. Children of Men', '60. Ratatouille', '61. The Lives of Others', '62. The Prestige', '63. V for Vendetta', '64. Chinatown', '65. City of God', '66. To Have and Have Not', '67. Fargo', '68. Life of Pi', '69. Slumdog Millionaire', '70. Vertigo', '71. Trainspotting', '72. Interstellar', '73. The Thing', '74. The Third Man', '75. 12 Monkeys', '76. Life Is Beautiful', '77. The Pianist', '78. Magnolia', '79. The Dark Knight Rises', '80. Star Wars: Episode VII - The Force Awakens', '81. The Hobbit: The Desolation of Smaug', '82. Mad Max: Fury Road', '83. 12 Years a Slave', '84. Indiana Jones and the Last Crusade', '85. O Brother, Where Art Thou?', '86. Inglourious Basterds', '87. The Departed', '88. A Beautiful Mind', '89. District 9', '90. The Piano', '91. Mystic River', '92. The Insider', '93. L.A. Confidential', '94. Heat', '95. The Usual Suspects', '96. Cool Hand Luke', '97. Eternal Sunshine of the Spotless Mind', '98. City Lights', '99. The Matrix', '100. Sin City', '101. Misery', "102. What's Eating Gilbert Grape", '103. Monty Python and the Holy Grail', '104. The Deer Hunter', '105. Scarface', '106. A Clockwork Orange', '107. The Elephant Man', '108. Papillon', '109. Lawrence of Arabia', '110. East of Eden', '111. Hotel Rwanda', '112. Dances with Wolves', '113. Pirates of the Caribbean: The Curse of the Black Pearl', '114. Batman Begins', '115. Skyfall', '116. The Treasure of the Sierra Madre', '117. The Untouchables', '118. The Truman Show', '119. Reservoir Dogs', '120. The Apartment', '121. The Big Sleep', '122. Amour', '123. The Grump', '124. Ben-Hur', '125. Happiness', '126. 8½', '127. Thelma & Louise', '128. Downfall', '129. Rocky', '130. Gran Torino', '131. Strangers on a Train', "132. Who's Afraid of Virginia Woolf?", '133. The Exorcist', '134. The Terminator', '135. The Hobbit: An Unexpected Journey', '136. Kill Bill: Vol. 2', '137. Gladiator', '138. Traffic', '139. Zodiac', '140. The Green Mile', '141. Avatar', '142. Halloween', '143. Casino', '144. Jaws', '145. Once Upon a Time in the West', '146. Notorious', '147. The Great Escape', '148. The Nightmare Before Christmas', '149. Goldfinger', '150. Death Proof', '151. Argo', '152. Milk', '153. Being John Malkovich', '154. Black Swan', '155. The Others', '156. Brokeback Mountain', '157. Collateral', '158. Jackie Brown', '159. Casino Royale', '160. Platoon', '161. The Thin Red Line', '162. The Hunger Games: Catching Fire', '163. The Godfather Part III', '164. American History X', '165. Dead Poets Society', '166. The Visitor', '167. Talk to Her', '168. The Girl with the Dragon Tattoo', '169. Das Boot', '170. Sideways', '171. Scent of a Woman', '172. Deliverance', '173. Taken', '174. Back to the Future Part II', '175. The Incredible Shrinking Man', '176. The Fugitive', '177. Shutter Island', '178. The Big Lebowski', '179. Last Tango in Paris', '180. The Talented Mr. Ripley', '181. First Blood', '182. The Ghost Writer', '183. Million Dollar Baby', "184. The Man Who Wasn't There", '185. The Wrestler', '186. Harry Brown', '187. The Bourne Identity', '188. La Cage aux Folles', '189. There Will Be Blood', '190. Billy Elliot', '191. Little Miss Sunshine', '192. The Hobbit: The Battle of the Five Armies', '193. The Hunger Games', '194. Psycho', '195. E.T. the Extra-Terrestrial', '196. Kramer vs. Kramer', '197. Under the Tuscan Sun', '198. Transamerica', '199. WALL·E', '200. Dirty Harry', '201. Star Wars: Episode III - Revenge of the Sith', '202. Stand by Me', '203. A Nightmare on Elm Street', '204. Finding Nemo', '205. In the Mouth of Madness', '206. The Fifth Element', '207. The Sixth Sense', '208. Amores Perros', '209. Jurassic Park', "210. Carlito's Way", '211. Army of Darkness', '212. A Fish Called Wanda', '213. Good Will Hunting', '214. Cat on a Hot Tin Roof', '215. Total Recall', '216. Crouching Tiger, Hidden Dragon', '217. Show Me Love', '218. 21 Grams', '219. Cape Fear', '220. Inside Man', '221. Sin City: A Dame to Kill For', '222. Groundhog Day', '223. JFK', '224. Black Hawk Down', '225. Bad Education', '226. Watchmen', '227. The 100 Year-Old Man Who Climbed Out the Window and Disappeared', '228. Lilya 4-Ever', '229. The Sea Inside', '230. Catch Me If You Can', '231. Man on the Moon', '232. Alive', '233. Spy Game', '234. Changeling', '235. The Reader', '236. Predator', '237. Heist', '238. The Bank Job', '239. Blue Velvet', '240. High Fidelity', '241. The Curious Case of Benjamin Button', '242. The English Patient', '243. The Wizard of Oz', '244. The Philadelphia Story', '245. Rio Bravo', '246. The Chorus', '247. Lord of War', '248. Lock, Stock and Two Smoking Barrels', '249. Big Fish', '250. Dead Alive'] 250

In [30]:
print(Year,len(Year))

['1972', '1991', '1980', '1994', '1980', '1942', '1975', '1981', '2003', '1977', '2008', '1974', '1986', '1993', '2010', '2001', '1979', '1959', '1982', '1995', '1979', '1957', '2002', '1991', '1983', '1988', '1939', '1976', '1994', '1957', '1994', '1959', '1954', '1994', '1985', '1941', '1990', '2000', '1999', '1997', '1994', '1952', '1995', '1998', '1988', '2010', '1968', '2003', '1972', '1966', '2001', '1936', '2003', '1987', '2000', '1999', '2007', '2012', '2006', '2007', '2006', '2006', '2005', '1974', '2002', '1944', '1996', '2012', '2008', '1958', '1996', '2014', '1982', '1949', '1995', '1997', '2002', '1999', '2012', '2015', '2013', '2015', '2013', '1989', '2000', '2009', '2006', '2001', '2009', '1993', '2003', '1999', '1997', '1995', '1995', '1967', '2004', '1931', '1999', '2005', '1990', '1993', '1975', '1978', '1983', '1971', '1980', '1973', '1962', '1955', '2004', '1990', '2003', '2005', '2012', '1948', '1987', '1998', '1992', '1960', '1946', '2012', '2014', '1959', '1998', '1963', '1991', '2004', '1976', '2008', '1951', '1966', '1973', '1984', '2012', '2004', '2000', '2000', '2007', '1999', '2009', '1978', '1995', '1975', '1968', '1946', '1963', '1993', '1964', '2007', '2012', '2008', '1999', '2010', '2001', '2005', '2004', '1997', '2006', '1986', '1998', '2013', '1990', '1998', '1989', '2007', '2002', '2009', '1981', '2004', '1992', '1972', '2008', '1989', '1957', '1993', '2010', '1998', '1972', '1999', '1982', '2010', '2004', '2001', '2008', '2009', '2002', '1978', '2007', '2000', '2006', '2014', '2012', '1960', '1982', '1979', '2003', '2005', '2008', '1971', '2005', '1986', '1984', '2003', '1994', '1997', '1999', '2000', '1993', '1993', '1992', '1988', '1997', '1958', '1990', '2000', '1998', '2003', '1991', '2006', '2014', '1993', '1991', '2001', '2004', '2009', '2013', '2002', '2004', '2002', '1999', '1993', '2001', '2008', '2008', '1987', '2001', '2008', '1986', '2000', '2008', '1996', '1939', '1940', '1959', '2004', '2005', '1998', '2003', '1992'] 250

In [31]:
print(Time,len(Time))

['2h 55m', '1h 58m', '2h 4m', '2h 22m', '2h 26m', '1h 42m', '2h 13m', '1h 55m', '3h 21m', '2h 1m', '2h 32m', '3h 22m', '2h 17m', '3h 15m', '2h 28m', '2h 58m', '1h 57m', '2h 1m', '1h 57m', '2h 7m', '2h 27m', '1h 36m', '2h 59m', '2h 17m', '2h 11m', '2h 12m', '3h 58m', '1h 54m', '2h 34m', '2h 41m', '1h 28m', '2h 16m', '1h 52m', '1h 50m', '1h 56m', '1h 59m', '2h 25m', '1h 53m', '2h 2m', '2h 19m', '2h 22m', '1h 43m', '2h 58m', '2h 49m', '2h 13m', '1h 58m', '2h 29m', '1h 51m', '2h 24m', '2h 58m', '2h 2m', '1h 27m', '1h 42m', '1h 56m', '1h 42m', '2h 19m', '2h 2m', '2h 45m', '1h 49m', '1h 51m', '2h 17m', '2h 10m', '2h 12m', '2h 10m', '2h 10m', '1h 40m', '1h 38m', '2h 7m', '2h', '2h 8m', '1h 33m', '2h 49m', '1h 49m', '1h 44m', '2h 9m', '1h 56m', '2h 30m', '3h 8m', '2h 44m', '2h 18m', '2h 41m', '2h', '2h 14m', '2h 7m', '1h 47m', '2h 33m', '2h 31m', '2h 15m', '1h 52m', '2h 1m', '2h 18m', '2h 37m', '2h 18m', '2h 50m', '1h 46m', '2h 7m', '1h 48m', '1h 27m', '2h 16m', '2h 4m', '1h 47m', '1h 58m', '1h 31m', '3h 3m', '2h 50m', '2h 16m', '2h 4m', '2h 31m', '3h 47m', '1h 58m', '2h 1m', '3h 1m', '2h 23m', '2h 20m', '2h 23m', '2h 6m', '1h 59m', '1h 43m', '1h 39m', '2h 5m', '1h 54m', '2h 7m', '1h 42m', '3h 32m', '2h 14m', '2h 18m', '2h 10m', '2h 36m', '2h', '1h 56m', '1h 41m', '2h 11m', '2h 2m', '1h 47m', '2h 49m', '2h 17m', '2h 35m', '2h 27m', '2h 37m', '3h 9m', '2h 42m', '1h 31m', '2h 58m', '2h 4m', '2h 46m', '1h 42m', '2h 52m', '1h 16m', '1h 50m', '2h 7m', '2h', '2h 8m', '1h 53m', '1h 48m', '1h 44m', '2h 14m', '2h', '2h 34m', '2h 24m', '2h', '2h 50m', '2h 26m', '2h 42m', '1h 59m', '2h 8m', '1h 44m', '1h 52m', '2h 32m', '2h 29m', '2h 7m', '2h 36m', '1h 49m', '1h 30m', '1h 48m', '1h 21m', '2h 10m', '2h 18m', '1h 57m', '2h 9m', '2h 19m', '1h 33m', '2h 8m', '2h 12m', '1h 56m', '1h 49m', '1h 43m', '1h 59m', '1h 37m', '2h 38m', '1h 50m', '1h 41m', '2h 24m', '2h 22m', '1h 49m', '1h 55m', '1h 45m', '1h 53m', '1h 43m', '1h 38m', '1h 42m', '2h 20m', '1h 29m', '1h 31m', '1h 40m', '1h 35m', '2h 6m', '1h 47m', '2h 34m', '2h 7m', '2h 24m', '1h 21m', '1h 48m', '2h 6m', '1h 48m', '1h 53m', '2h', '1h 29m', '2h 4m', '2h 8m', '2h 9m', '1h 42m', '1h 41m', '3h 9m', '2h 24m', '1h 46m', '2h 42m', '1h 54m', '1h 49m', '2h 6m', '2h 21m', '1h 58m', '2h 8m', '2h 6m', '2h 21m', '2h 4m', '1h 47m', '1h 49m', '1h 51m', '2h', '1h 53m', '2h 46m', '2h 42m', '1h 42m', '1h 52m', '2h 21m', '1h 37m', '2h 2m', '1h 47m', '2h 5m', '1h 44m'] 250

In [32]:
for i in range(len(metascore)):
    if i in [49,123,150]:
        metascore.insert(i,np.nan)

In [33]:
print(metascore,len(metascore))

['100', '86', '82', '82', '68', '100', '84', '86', '94', '90', '84', '90', '84', '95', '74', '92', '89', '98', '84', '65', '94', '97', '87', '75', '58', '72', '97', '94', '95', '88', '88', '98', '100', '64', '87', '100', '92', '83', '84', '67', '82', '99', '68', '91', '65', '88', '84', '69', '90', nan, '70', '96', '91', '78', '71', '67', '92', '81', '84', '96', '89', '66', '62', '92', '79', '90', '88', '79', '84', '100', '83', '74', '57', '97', '75', '58', '85', '78', '78', '80', '66', '90', '96', '65', '69', '69', '85', '72', '81', '89', '84', '85', '91', '76', '76', '92', '89', '99', '73', '74', '75', '73', '91', '90', '65', '77', '78', '58', '100', '72', '79', '72', '63', '70', '81', '98', '79', '90', '81', '94', '86', '95', '90', nan, '81', '93', '89', '82', '70', '73', '88', '75', '83', '84', '58', '83', '67', '86', '79', '61', '83', '90', '73', '87', '82', '100', '86', '82', '87', '86', nan, '83', '90', '79', '74', '87', '71', '62', '80', '92', '78', '76', '60', '62', '79', '79', '86', '76', '85', '94', '57', '80', '51', '57', '73', '87', '63', '71', '77', '76', '61', '77', '86', '73', '80', '55', '68', '61', '93', '74', '80', '59', '68', '97', '92', '77', '52', '66', '95', '87', '68', '75', '76', '90', '53', '52', '64', '83', '68', '66', '59', '80', '71', '84', '60', '94', '73', '70', '73', '76', '46', '72', '72', '74', '81', '56', '58', '83', '74', '75', '58', '56', '63', '63', '58', '47', '66', '69', '75', '79', '70', '86', '92', '96', '93', '56', '62', '67', '58', '54'] 250

In [34]:
print(Rating,len(Rating))

['9.2', '8.6', '8.7', '9.3', '8.4', '8.5', '8.7', '8.4', '9.0', '8.6', '9.0', '9.0', '8.4', '9.0', '8.8', '8.9', '8.5', '8.2', '8.1', '8.6', '8.4', '9.0', '8.8', '8.6', '8.3', '8.2', '8.2', '8.2', '8.9', '8.1', '8.5', '8.3', '8.5', '8.5', '8.5', '8.3', '8.7', '8.4', '8.3', '7.7', '8.8', '8.3', '8.3', '8.6', '8.0', '8.0', '8.3', '8.2', '7.2', '8.8', '8.3', '8.5', '7.7', '8.2', '8.3', '8.8', '8.2', '8.5', '7.9', '8.1', '8.4', '8.5', '8.1', '8.1', '8.6', '7.8', '8.1', '7.9', '8.0', '8.2', '8.1', '8.7', '8.2', '8.1', '8.0', '8.6', '8.5', '8.0', '8.4', '7.8', '7.8', '8.1', '8.1', '8.2', '7.7', '8.4', '8.5', '8.2', '7.9', '7.5', '7.9', '7.8', '8.2', '8.3', '8.5', '8.0', '8.3', '8.5', '8.7', '8.0', '7.8', '7.7', '8.2', '8.1', '8.3', '8.2', '8.2', '8.0', '8.3', '7.8', '8.1', '8.0', '8.1', '8.2', '7.8', '8.2', '7.8', '8.2', '8.3', '8.3', '7.9', '7.9', '6.7', '8.1', '7.7', '8.0', '7.6', '8.2', '8.1', '8.1', '7.9', '8.0', '8.1', '8.1', '7.8', '8.0', '8.5', '7.5', '7.7', '8.6', '7.9', '7.7', '8.2', '8.1', '8.5', '7.9', '8.2', '7.9', '7.7', '7.0', '7.7', '7.5', '7.7', '8.0', '7.6', '7.7', '7.5', '7.5', '8.0', '8.1', '7.6', '7.5', '7.6', '8.5', '8.1', '7.6', '7.9', '7.8', '8.4', '7.5', '8.0', '7.6', '7.7', '7.8', '7.6', '7.8', '8.2', '8.1', '6.8', '7.4', '7.7', '7.2', '8.1', '7.5', '7.9', '7.2', '7.8', '7.2', '8.2', '7.7', '7.8', '7.4', '7.2', '8.5', '7.9', '7.8', '6.7', '7.3', '8.4', '7.7', '7.6', '8.1', '7.4', '8.2', '7.1', '7.6', '8.2', '8.0', '8.2', '7.9', '7.4', '7.5', '8.3', '7.9', '7.5', '7.9', '7.5', '7.6', '7.3', '7.6', '6.5', '8.0', '8.0', '7.7', '7.4', '7.6', '7.0', '7.8', '8.0', '8.1', '7.4', '7.1', '7.1', '7.7', '7.6', '7.8', '6.5', '7.2', '7.7', '7.4', '7.8', '7.4', '8.1', '7.8', '8.0', '7.8', '7.6', '8.1', '8.0', '7.5'] 250

In [35]:
print(Imdb_votes,len(Imdb_votes))

['2.1M', '1.6M', '1.4M', '3M', '1.2M', '630K', '1.1M', '1.1M', '2.1M', '1.5M', '3M', '1.4M', '807K', '1.5M', '2.7M', '2.1M', '1M', '295K', '853K', '1.9M', '741K', '923K', '1.9M', '1.2M', '1.2M', '989K', '346K', '977K', '2.3M', '241K', '1.2M', '360K', '545K', '1.3M', '1.4M', '480K', '1.3M', '1.4M', '1.2M', '328K', '2.4M', '272K', '1.1M', '1.6M', '564K', '721K', '752K', '1.2M', '12K', '851K', '818K', '272K', '510K', '821K', '937K', '2.5M', '1.1M', '1.8M', '547K', '883K', '427K', '1.5M', '1.2M', '364K', '836K', '40K', '755K', '684K', '895K', '444K', '748K', '2.3M', '497K', '189K', '663K', '777K', '966K', '338K', '1.9M', '998K', '731K', '1.2M', '764K', '837K', '341K', '1.7M', '1.5M', '1M', '735K', '98K', '503K', '186K', '640K', '756K', '1.2M', '194K', '1.1M', '207K', '2.2M', '807K', '249K', '262K', '587K', '375K', '963K', '910K', '272K', '142K', '329K', '50K', '383K', '301K', '1.3M', '1.6M', '750K', '137K', '343K', '1.3M', '1.1M', '209K', '93K', '108K', '3.1K', '263K', '77K', '129K', '183K', '388K', '659K', '838K', '145K', '82K', '477K', '963K', '902K', '837K', '1.8M', '225K', '634K', '1.5M', '1.4M', '323K', '591K', '693K', '367K', '111K', '268K', '395K', '209K', '324K', '652K', '183K', '362K', '858K', '409K', '400K', '448K', '389K', '717K', '456K', '206K', '747K', '439K', '1.2M', '589K', '45K', '120K', '227K', '279K', '211K', '350K', '124K', '655K', '597K', '21K', '333K', '1.5M', '889K', '61K', '261K', '289K', '174K', '745K', '118K', '326K', '93K', '594K', '12K', '670K', '148K', '537K', '596K', '1M', '751K', '453K', '161K', '63K', '43K', '1.3M', '175K', '879K', '464K', '277K', '1.2M', '84K', '526K', '1.1M', '267K', '1.1M', '240K', '202K', '160K', '1.1M', '55K', '368K', '288K', '57K', '250K', '226K', '412K', '175K', '715K', '176K', '439K', '65K', '597K', '43K', '52K', '87K', '1.2M', '141K', '67K', '172K', '271K', '268K', '476K', '40K', '193K', '232K', '195K', '721K', '209K', '450K', '76K', '71K', '69K', '349K', '634K', '469K', '107K'] 250

In [36]:
Description=[]

In [37]:
for i in range(1,len(Movie_description)):
    Description.append(Movie_description[i])

In [38]:
print(Description,len(Description))

['The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.', 'After the Empire overpowers the Rebel Alliance, Luke Skywalker begins training with Jedi Master Yoda, while Darth Vader and bounty hunter Boba Fett pursue his friends across the galaxy.', 'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.', 'A family heads to an isolated hotel for the winter, where a sinister presence influences the father into violence. At the same time, his psychic son sees horrifying forebodings from both the past and the future.', 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.', 'A newly admitted mental patient helps his docile companions defy the tyrannical head nurse.', 'In 1936, archaeologists and adventurers of the U.S. government hired Indiana Jones to find the Ark of the Covenant before the Nazis could obtain its extraordinary powers.', "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.", "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.", 'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.', 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.', 'Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony but finds herself battling the Alien Queen and her offspring.', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 'After investigating a mysterious transmission of unknown origin, the crew of a commercial spacecraft encounters a deadly lifeform.', 'After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.', 'A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.', 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.', 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.', 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.', "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.", 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten year old son John from an even more advanced and powerful cyborg.', 'After rescuing Han Solo from Jabba the Hutt, the Rebel Alliance attempts to destroy the second Death Star while Luke struggles to help Darth Vader back from the dark side.', 'A New York City police officer tries to save his estranged wife and several others taken hostage by terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.', 'A sheltered and manipulative Southern belle and a roguish profiteer face off in a turbulent romance as the society around them crumbles with the end of slavery and is rebuilt during the Civil War and Reconstruction periods.', 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'British POWs are forced to build a railway bridge across the river Kwai for their Japanese captors in occupied Burma, not knowing that the allied forces are planning a daring commando raid through the jungle to destroy it.', 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 'A New York City advertising executive goes on the run after being mistaken for a government agent by a group of foreign spies, and falls for a woman whose loyalties he begins to doubt.', 'A bored photographer recovering from a broken leg passes the time by watching his neighbors and begins to suspect one of them of murder.', 'An Italian hit man protects a New York orphan.', 'Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.', "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance: 'Rosebud.'", 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.', "A former insurance investigator who now suffers from anterograde amnesia uses notes and tattoos to hunt down his wife's murderer.", "A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.", 'A single mother and waitress, a misanthropic author, and a gay artist form an unlikely friendship after the artist is assaulted in a robbery.', "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.", 'A silent film star falls for a chorus girl just as he and his delusionally jealous screen partner are trying to make the difficult transition to talking pictures in 1920s Hollywood.', 'Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.', 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', "After a selfish L.A. yuppie learns his estranged father left a fortune to an autistic-savant brother in Ohio that he didn't know existed, he absconds with his brother and sets out across the country, hoping to gain a larger inheritance.", 'The story of King George VI, his unexpected ascension to the throne of the British Empire in 1936, and the speech therapist who helped the unsure monarch overcome his stammer.', 'When a mysterious artifact is uncovered on the Moon, a spacecraft manned by two humans and one supercomputer is sent to Jupiter to find its origins.', 'After waking from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.', "A successful businessman goes to Italy to arrange for the return of his tycoon father's body--and discovers that Dad died with his long-time mistress.", 'A bounty-hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', 'Despite being caught in her imaginative world, young waitress Amelie decides to help people find happiness. Her quest to spread joy leads her on a journey during which she finds true love.', 'The Tramp struggles to live in modern industrial society with the help of a young homeless woman.', 'A fading movie star falls for a lonely young woman in Tokyo.', 'A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.', 'The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 'Violence and mayhem ensue after a hunter stumbles upon the aftermath of a drug deal gone wrong and over two million dollars in cash near the Rio Grande.', 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.', 'In 2027, in a chaotic world in which women have somehow become infertile, a former activist agrees to help transport a miraculously pregnant woman to a sanctuary at sea.', 'A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.', 'In 1984 East Berlin, an agent of the secret police conducting surveillance on a writer and his lover finds himself becoming increasingly absorbed by their lives.', 'Rival 19th-century magicians engage in a bitter battle for trade secrets.', 'In a future British dystopian society, a shadowy freedom fighter, known only by the alias of "V", plots to overthrow the tyrannical government - with the help of a young woman.', 'A private detective hired to expose an adulterer in 1930s Los Angeles finds himself caught up in a web of deceit, corruption, and murder.', "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.", 'During World War II, an American expatriate helps transport a French Resistance leader and his wife to Martinique while romancing a lounge singer.', "Minnesota car salesman Jerry Lundegaard's inept crime falls apart due to his and his henchmen's bungling and the persistent police work of the quite pregnant Marge Gunderson.", 'A young man who survives a disaster at sea is hurtled into an epic journey of adventure and discovery. While cast away, he forms an unexpected connection with another survivor: a fearsome Bengal tiger.', 'When a teenager from the slums of Mumbai is interrogated about his suspicious performance on a quiz show, he revisits various events from his past to explain how he knew all the answers.', 'A former San Francisco police detective juggles wrestling with his personal demons and becoming obsessed with the hauntingly beautiful woman he has been hired to trail, who may be deeply disturbed.', 'Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out despite the allure of drugs and the influence of friends.', 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.', 'A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.', 'Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend, Harry Lime.', 'In a future world devastated by disease, a convict is sent back in time to gather information about the man-made virus that wiped out most of the human population on the planet.', 'When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.', 'During WWII, acclaimed Polish musician Wladyslaw faces various struggles as he loses contact with his family. As the situation worsens, he hides in the ruins of Warsaw in order to survive.', 'An epic mosaic of interrelated characters in search of love, forgiveness and meaning in the San Fernando Valley.', 'Bane, an imposing terrorist, attacks Gotham City and disrupts its eight-year-long period of peace. This forces Bruce Wayne to come out of hiding and don the cape and cowl of Batman again.', 'As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.', 'The dwarves, along with Bilbo Baggins and Gandalf the Grey, continue their quest to reclaim the Lonely Mountain, their homeland, from the dragon Smaug.', 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshipper and a drifter named Max.', 'In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.', 'In 1938, after his father goes missing while pursuing the Holy Grail, Indiana Jones finds himself up against the Nazis again to stop them from obtaining its powers.', 'In the deep south during the 1930s, three escaped convicts search for hidden treasure while a relentless lawman pursues them.', "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.", 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.', 'A mathematical genius, John Nash made an astonishing discovery early in his career and stood on the brink of international acclaim. But the handsome and arrogant Nash soon found himself on a harrowing journey of self-discovery.', 'In a future Earth in which aliens are isolated in a remote ghetto, a government agent finds himself banished there.', 'In the mid-19th century a mute woman is sent to New Zealand along with her young daughter and prized piano for an arranged marriage to a farmer, but is soon lusted after by a farm worker.', "The tragic murder of a 19-year-old girl reunites three childhood friends still living in Boston--the victim's gangster father, a detective, and the disturbed man they both suspect of killing her.", 'A research chemist comes under personal and professional attack when he decides to appear in a 60 Minutes exposé on Big Tobacco.', 'As corruption grows in 1950s Los Angeles, three policemen - one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice.', 'A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a verbal clue at their latest heist.', 'The sole survivor of a pier shoot-out tells the story of how a notorious criminal influenced the events that began with five criminals meeting in a seemingly random police lineup.', 'A laid-back Southern man is sentenced to two years in a rural prison, but refuses to conform.', 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories forever.', 'With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a sightless flower girl accumulates money to be able to help her medically.', 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.', 'An exploration of the dark and miserable Basin City and three of its residents, all of whom are caught up in violent corruption.', 'After a famous author is rescued from a car crash by a fan of his novels, he comes to realize that the care he is receiving is only the beginning of a nightmare of captivity and abuse.', 'A young man in a small Midwestern town struggles to care for his mentally-disabled younger brother and morbidly obese mother while attempting to pursue his own happiness.', 'King Arthur and his Knights of the Round Table embark on a surreal, low-budget search for the Holy Grail, encountering many, very silly obstacles.', 'An in-depth examination of the ways in which the Vietnam War impacts and disrupts the lives of several friends in a small steel mill town in Pennsylvania.', 'In the 1980s, a determined criminal-minded Cuban immigrant becomes the biggest drug smuggler in Miami, and is eventually undone by his own drug addiction.', 'Alex DeLarge and his droogs barbarize a decaying near-future.', 'A Victorian surgeon rescues a heavily disfigured man who is mistreated while scraping a living as a side-show freak. Behind his monstrous façade, there is revealed a person of kindness, intelligence and sophistication.', "A French convict in the 1930s befriends a fellow criminal as the two of them begin serving their sentence in the South American penal colony on Devil's Island, which inspires the man to plot his escape.", 'The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I in order to fight the Turks.', 'Two brothers in 1910s California struggle to maintain the favor of their affectionate but strict, Bible-toting father as an old secret about their long-absent mother comes to light.', 'Paul Rusesabagina, a hotel manager, houses over a thousand Tutsi refugees during their struggle against the Hutu militia in Rwanda, Africa.', 'A lieutenant assigned to a remote Civil War outpost starts questioning his purpose after making contact with a neighboring Sioux settlement.', 'Blacksmith Will Turner teams up with eccentric pirate "Captain" Jack Sparrow to save Elizabeth Swann, the governor\'s daughter and his love, from Jack\'s former pirate allies, who are now undead.', "After witnessing his parents' death, billionaire Bruce Wayne learns the art of fighting to confront injustice. When he returns to Gotham as Batman, he must stop a secret society that intends to destroy the city.", "James Bond's loyalty to M is tested when her past comes back to haunt her. When MI6 comes under attack, 007 must track down and destroy the threat, no matter how personal the cost.", 'Two down-on-their-luck Americans searching for work in 1920s Mexico convince an old prospector to help them mine for gold in the Sierra Madre Mountains.', 'During Prohibition, Treasury agent Eliot Ness sets out to stop ruthless Chicago gangster Al Capone, and assembles a small, incorruptible team to help him.', 'An insurance salesman begins to suspect that his whole life is actually some sort of reality TV show.', 'When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.', 'A Manhattan insurance clerk tries to rise in his company by letting its executives use his apartment for trysts, but office politics and his own romantic hopes complicate matters.', "Private detective Philip Marlowe is hired by a wealthy family. Before the complex case is over, he's seen murder, blackmail--and what might be love.", "Georges and Anne are an octogenarian couple. They are cultivated, retired music teachers. Their daughter, also a musician, lives in Britain with her family. One day, Anne has a stroke, and the couple's bond of love is severely tested.", "A grumpy old man who hates post-1953 changes falls and must spend a weekend in Helsinki. His injury forces family time and involvement in his daughter-in-law's business deal, while confronting his own failings as a father.", "A Jewish prince is betrayed and sent into slavery by a Roman friend in 1st-century Jerusalem, but it's not long before he regains his freedom and comes back for revenge.", 'The lives of several individuals intertwine a

In [39]:
Movie_director=[]
data6=np.array(director)
for i in data6.flatten():
    Movie_director.append(i)

In [40]:
print(Movie_director,len(Movie_director))

['Francis Ford Coppola', 'Jonathan Demme', 'Irvin Kershner', 'Frank Darabont', 'Stanley Kubrick', 'Michael Curtiz', 'Milos Forman', 'Steven Spielberg', 'Peter Jackson', 'George Lucas', 'Christopher Nolan', 'Francis Ford Coppola', 'James Cameron', 'Steven Spielberg', 'Christopher Nolan', 'Peter Jackson', 'Ridley Scott', 'Billy Wilder', 'Ridley Scott', 'David Fincher', 'Francis Ford Coppola', 'Sidney Lumet', 'Peter Jackson', 'James Cameron', 'Richard Marquand', 'John McTiernan', 'Victor Fleming', 'Martin Scorsese', 'Quentin Tarantino', 'David Lean', 'sRoger AllersRob Minkoff', 'Alfred Hitchcock', 'Alfred Hitchcock', 'Luc Besson', 'Robert Zemeckis', 'Orson Welles', 'Martin Scorsese', 'Christopher Nolan', 'Sam Mendes', 'James L. Brooks', 'Robert Zemeckis', 'sStanley DonenGene Kelly', 'Mel Gibson', 'Steven Spielberg', 'Barry Levinson', 'Tom Hooper', 'Stanley Kubrick', 'Quentin Tarantino', 'Billy Wilder', 'Sergio Leone', 'Jean-Pierre Jeunet', 'Charles Chaplin', 'Sofia Coppola', 'Stanley Kubrick', 'Darren Aronofsky', 'David Fincher', 'sEthan CoenJoel Coen', 'Quentin Tarantino', 'Alfonso Cuarón', 'sBrad BirdJan Pinkava', 'Florian Henckel von Donnersmarck', 'Christopher Nolan', 'James McTeigue', 'Roman Polanski', 'sFernando MeirellesKátia Lund', 'Howard Hawks', 'sJoel CoenEthan Coen', 'Ang Lee', 'sDanny BoyleLoveleen Tandan', 'Alfred Hitchcock', 'Danny Boyle', 'Christopher Nolan', 'John Carpenter', 'Carol Reed', 'Terry Gilliam', 'Roberto Benigni', 'Roman Polanski', 'Paul Thomas Anderson', 'Christopher Nolan', 'J.J. Abrams', 'Peter Jackson', 'George Miller', 'Steve McQueen', 'Steven Spielberg', 'sJoel CoenEthan Coen', 'Quentin Tarantino', 'Martin Scorsese', 'Ron Howard', 'Neill Blomkamp', 'Jane Campion', 'Clint Eastwood', 'Michael Mann', 'Curtis Hanson', 'Michael Mann', 'Bryan Singer', 'Stuart Rosenberg', 'Michel Gondry', 'Charles Chaplin', 'sLana WachowskiLilly Wachowski', 'sFrank MillerQuentin TarantinoRobert Rodriguez', 'Rob Reiner', 'Lasse Hallström', 'sTerry GilliamTerry Jones', 'Michael Cimino', 'Brian De Palma', 'Stanley Kubrick', 'David Lynch', 'Franklin J. Schaffner', 'David Lean', 'Elia Kazan', 'Terry George', 'Kevin Costner', 'Gore Verbinski', 'Christopher Nolan', 'Sam Mendes', 'John Huston', 'Brian De Palma', 'Peter Weir', 'Quentin Tarantino', 'Billy Wilder', 'Howard Hawks', 'Michael Haneke', 'Dome Karukoski', 'William Wyler', 'Todd Solondz', 'Federico Fellini', 'Ridley Scott', 'Oliver Hirschbiegel', 'John G. Avildsen', 'Clint Eastwood', 'Alfred Hitchcock', 'Mike Nichols', 'William Friedkin', 'James Cameron', 'Peter Jackson', 'Quentin Tarantino', 'Ridley Scott', 'Steven Soderbergh', 'David Fincher', 'Frank Darabont', 'James Cameron', 'John Carpenter', 'Martin Scorsese', 'Steven Spielberg', 'Sergio Leone', 'Alfred Hitchcock', 'John Sturges', 'Henry Selick', 'Guy Hamilton', 'Quentin Tarantino', 'Ben Affleck', 'Gus Van Sant', 'Spike Jonze', 'Darren Aronofsky', 'Alejandro Amenábar', 'Ang Lee', 'Michael Mann', 'Quentin Tarantino', 'Martin Campbell', 'Oliver Stone', 'Terrence Malick', 'Francis Lawrence', 'Francis Ford Coppola', 'Tony Kaye', 'Peter Weir', 'Tom McCarthy', 'Pedro Almodóvar', 'Niels Arden Oplev', 'Wolfgang Petersen', 'Alexander Payne', 'Martin Brest', 'John Boorman', 'Pierre Morel', 'Robert Zemeckis', 'Jack Arnold', 'Andrew Davis', 'Martin Scorsese', 'sJoel CoenEthan Coen', 'Bernardo Bertolucci', 'Anthony Minghella', 'Ted Kotcheff', 'Roman Polanski', 'Clint Eastwood', 'Joel Coen', 'Darren Aronofsky', 'Daniel Barber', 'Doug Liman', 'Édouard Molinaro', 'Paul Thomas Anderson', 'Stephen Daldry', 'sJonathan DaytonValerie Faris', 'Peter Jackson', 'Gary Ross', 'Alfred Hitchcock', 'Steven Spielberg', 'Robert Benton', 'Audrey Wells', 'Duncan Tucker', 'Andrew Stanton', 'sDon SiegelClint Eastwood', 'George Lucas', 'Rob Reiner', 'Wes Craven', 'sAndrew StantonLee Unkrich', 'John Carpenter', 'Luc Besson', 'M. Night Shyamalan', 'Alejandro G. Iñárritu', 'Steven Spielberg', 'Brian De Palma', 'Sam Raimi', 'sCharles CrichtonJohn Cleese', 'Gus Van Sant', 'Richard Brooks', 'Paul Verhoeven', 'Ang Lee', 'Lukas Moodysson', 'Alejandro G. Iñárritu', 'Martin Scorsese', 'Spike Lee', 'sFrank MillerRobert Rodriguez', 'Harold Ramis', 'Oliver Stone', 'Ridley Scott', 'Pedro Almodóvar', 'Zack Snyder', 'Felix Herngren', 'Lukas Moodysson', 'Alejandro Amenábar', 'Steven Spielberg', 'Milos Forman', 'Frank Marshall', 'Tony Scott', 'Clint Eastwood', 'Stephen Daldry', 'John McTiernan', 'David Mamet', 'Roger Donaldson', 'David Lynch', 'Stephen Frears', 'David Fincher', 'Anthony Minghella', 'sVictor FlemingKing Vidor', 'George Cukor', 'Howard Hawks', 'Christophe Barratier', 'Andrew Niccol', 'Guy Ritchie', 'Tim Burton', 'Peter Jackson'] 250

In [41]:
Movie_actors=[]
data7=np.array(actors)
for i in data7.flatten():
    Movie_actors.append(i)

In [42]:
print(Movie_actors,len(Movie_actors))

['Marlon BrandoAl PacinoJames Caan', 'Jodie FosterAnthony HopkinsScott Glenn', 'Mark HamillHarrison FordCarrie Fisher', 'Tim RobbinsMorgan FreemanBob Gunton', 'Jack NicholsonShelley DuvallDanny Lloyd', 'Humphrey BogartIngrid BergmanPaul Henreid', 'Jack NicholsonLouise FletcherMichael Berryman', 'Harrison FordKaren AllenPaul Freeman', 'Elijah WoodViggo MortensenIan McKellen', 'Mark HamillHarrison FordCarrie Fisher', 'Christian BaleHeath LedgerAaron Eckhart', 'Al PacinoRobert De NiroRobert Duvall', 'Sigourney WeaverMichael BiehnCarrie Henn', 'Liam NeesonRalph FiennesBen Kingsley', 'Leonardo DiCaprioJoseph Gordon-LevittElliot Page', 'Elijah WoodIan McKellenOrlando Bloom', 'Sigourney WeaverTom SkerrittJohn Hurt', 'Marilyn MonroeTony CurtisJack Lemmon', 'Harrison FordRutger HauerSean Young', 'Morgan FreemanBrad PittKevin Spacey', 'Martin SheenMarlon BrandoRobert Duvall', 'Henry FondaLee J. CobbMartin Balsam', 'Elijah WoodIan McKellenViggo Mortensen', 'Arnold SchwarzeneggerLinda HamiltonEdward Furlong', 'Mark HamillHarrison FordCarrie Fisher', 'Bruce WillisAlan RickmanBonnie Bedelia', 'Clark GableVivien LeighThomas Mitchell', 'Robert De NiroJodie FosterCybill Shepherd', 'John TravoltaUma ThurmanSamuel L. Jackson', 'William HoldenAlec GuinnessJack Hawkins', 'Matthew BroderickJeremy IronsJames Earl Jones', 'Cary GrantEva Marie SaintJames Mason', 'James StewartGrace KellyWendell Corey', 'Jean RenoGary OldmanNatalie Portman', 'Michael J. FoxChristopher LloydLea Thompson', 'Orson WellesJoseph CottenDorothy Comingore', 'Robert De NiroRay LiottaJoe Pesci', 'Guy PearceCarrie-Anne MossJoe Pantoliano', 'Kevin SpaceyAnnette BeningThora Birch', 'Jack NicholsonHelen HuntGreg Kinnear', 'Tom HanksRobin WrightGary Sinise', "Gene KellyDonald O'ConnorDebbie Reynolds", 'Mel GibsonSophie MarceauPatrick McGoohan', 'Tom HanksMatt DamonTom Sizemore', 'Dustin HoffmanTom CruiseValeria Golino', 'Colin FirthGeoffrey RushHelena Bonham Carter', 'Keir DulleaGary LockwoodWilliam Sylvester', 'Uma ThurmanDavid CarradineDaryl Hannah', 'Jack LemmonJuliet MillsClive Revill', 'Clint EastwoodEli WallachLee Van Cleef', 'Audrey TautouMathieu KassovitzRufus', 'Charles ChaplinPaulette GoddardHenry Bergman', 'Bill MurrayScarlett JohanssonGiovanni Ribisi', "Matthew ModineR. Lee ErmeyVincent D'Onofrio", 'Ellen BurstynJared LetoJennifer Connelly', 'Brad PittEdward NortonMeat Loaf', 'Tommy Lee JonesJavier BardemJosh Brolin', 'Jamie FoxxChristoph WaltzLeonardo DiCaprio', 'Julianne MooreClive OwenChiwetel Ejiofor', 'Brad GarrettLou RomanoPatton Oswalt', 'Ulrich MüheMartina GedeckSebastian Koch', 'Christian BaleHugh JackmanScarlett Johansson', 'Hugo WeavingNatalie PortmanRupert Graves', 'Jack NicholsonFaye DunawayJohn Huston', 'Alexandre RodriguesLeandro FirminoMatheus Nachtergaele', 'Humphrey BogartLauren BacallWalter Brennan', 'William H. MacyFrances McDormandSteve Buscemi', 'Suraj SharmaIrrfan KhanAdil Hussain', 'Dev PatelFreida PintoSaurabh Shukla', 'James StewartKim NovakBarbara Bel Geddes', 'Ewan McGregorEwen BremnerJonny Lee Miller', 'Matthew McConaugheyAnne HathawayJessica Chastain', 'Kurt RussellWilford BrimleyKeith David', 'Orson WellesJoseph CottenAlida Valli', 'Bruce WillisMadeleine StoweBrad Pitt', 'Roberto BenigniNicoletta BraschiGiorgio Cantarini', 'Adrien BrodyThomas KretschmannFrank Finlay', 'Tom CruiseJason RobardsJulianne Moore', 'Christian BaleTom HardyAnne Hathaway', 'Daisy RidleyJohn BoyegaOscar Isaac', 'Ian McKellenMartin FreemanRichard Armitage', 'Tom HardyCharlize TheronNicholas Hoult', 'Chiwetel EjioforMichael Kenneth WilliamsMichael Fassbender', 'Harrison FordSean ConneryAlison Doody', 'George ClooneyJohn TurturroTim Blake Nelson', 'Brad PittDiane KrugerEli Roth', 'Leonardo DiCaprioMatt DamonJack Nicholson', 'Russell CroweEd HarrisJennifer Connelly', 'Sharlto CopleyDavid JamesJason Cope', 'Holly HunterHarvey KeitelSam Neill', 'Sean PennTim RobbinsKevin Bacon', 'Russell CroweAl PacinoChristopher Plummer', 'Kevin SpaceyRussell CroweGuy Pearce', 'Al PacinoRobert De NiroVal Kilmer', 'Kevin SpaceyGabriel ByrneChazz Palminteri', 'Paul NewmanGeorge KennedyStrother Martin', 'Jim CarreyKate WinsletTom Wilkinson', 'Charles ChaplinVirginia CherrillFlorence Lee', 'Keanu ReevesLaurence FishburneCarrie-Anne Moss', 'Mickey RourkeClive OwenBruce Willis', 'James CaanKathy BatesRichard Farnsworth', 'Johnny DeppLeonardo DiCaprioJuliette Lewis', 'Graham ChapmanJohn CleeseEric Idle', 'Robert De NiroChristopher WalkenJohn Cazale', 'Al PacinoMichelle PfeifferSteven Bauer', 'Malcolm McDowellPatrick MageeMichael Bates', 'Anthony HopkinsJohn HurtAnne Bancroft', 'Steve McQueenDustin HoffmanVictor Jory', "Peter O'TooleAlec GuinnessAnthony Quinn", 'James DeanRaymond MasseyJulie Harris', 'Don CheadleSophie OkonedoJoaquin Phoenix', 'Kevin CostnerMary McDonnellGraham Greene', 'Johnny DeppGeoffrey RushOrlando Bloom', 'Christian BaleMichael CaineKen Watanabe', 'Daniel CraigJavier BardemNaomie Harris', 'Humphrey BogartWalter HustonTim Holt', 'Kevin CostnerSean ConneryRobert De Niro', 'Jim CarreyEd HarrisLaura Linney', 'Harvey KeitelTim RothMichael Madsen', 'Jack LemmonShirley MacLaineFred MacMurray', 'Humphrey BogartLauren BacallJohn Ridgely', 'Jean-Louis TrintignantEmmanuelle RivaIsabelle Huppert', 'Antti LitjaPetra FreyMari Perankoski', 'Charlton HestonJack HawkinsStephen Boyd', 'Jane AdamsJon LovitzPhilip Seymour Hoffman', 'Marcello MastroianniAnouk AiméeClaudia Cardinale', 'Susan SarandonGeena DavisHarvey Keitel', 'Bruno GanzAlexandra Maria LaraUlrich Matthes', 'Sylvester StalloneTalia ShireBurt Young', 'Clint EastwoodBee VangChristopher Carley', 'Farley GrangerRobert WalkerRuth Roman', 'Elizabeth TaylorRichard BurtonGeorge Segal', 'Ellen BurstynMax von SydowLinda Blair', 'Arnold SchwarzeneggerLinda HamiltonMichael Biehn', 'Martin FreemanIan McKellenRichard Armitage', 'Uma ThurmanDavid CarradineMichael Madsen', 'Russell CroweJoaquin PhoenixConnie Nielsen', 'Michael DouglasBenicio Del ToroCatherine Zeta-Jones', 'Jake GyllenhaalRobert Downey Jr.Mark Ruffalo', 'Tom HanksMichael Clarke DuncanDavid Morse', 'Sam WorthingtonZoe SaldañaSigourney Weaver', 'Donald PleasenceJamie Lee CurtisTony Moran', 'Robert De NiroSharon StoneJoe Pesci', 'Roy ScheiderRobert ShawRichard Dreyfuss', 'Henry FondaCharles BronsonClaudia Cardinale', 'Cary GrantIngrid BergmanClaude Rains', 'Steve McQueenJames GarnerRichard Attenborough', "Danny ElfmanChris SarandonCatherine O'Hara", 'Sean ConneryGert FröbeHonor Blackman', 'Kurt RussellZoë BellRosario Dawson', 'Ben AffleckBryan CranstonJohn Goodman', 'Sean PennJosh BrolinEmile Hirsch', 'John CusackCameron DiazCatherine Keener', 'Natalie PortmanMila KunisVincent Cassel', 'Nicole KidmanChristopher EcclestonFionnula Flanagan', 'Jake GyllenhaalHeath LedgerMichelle Williams', 'Tom CruiseJamie FoxxJada Pinkett Smith', 'Pam GrierSamuel L. JacksonRobert Forster', 'Daniel CraigEva GreenJudi Dench', 'Charlie SheenTom BerengerWillem Dafoe', 'Jim CaviezelSean PennNick Nolte', 'Jennifer LawrenceJosh HutchersonLiam Hemsworth', 'Al PacinoDiane KeatonAndy Garcia', "Edward NortonEdward FurlongBeverly D'Angelo", 'Robin WilliamsRobert Sean LeonardEthan Hawke', 'Richard JenkinsHaaz SleimanDanai Gurira', 'Rosario FloresJavier CámaraDarío Grandinetti', 'Michael NyqvistNoomi RapaceEwa Fröling', 'Jürgen ProchnowHerbert GrönemeyerKlaus Wennemann', 'Paul GiamattiThomas Haden ChurchVirginia Madsen', "Al PacinoChris O'DonnellJames Rebhorn", 'Jon VoightBurt ReynoldsNed Beatty', 'Liam NeesonMaggie GraceFamke Janssen', 'Michael J. FoxChristopher LloydLea Thompson', 'Grant WilliamsRandy StuartApril Kent', 'Harrison FordTommy Lee JonesSela Ward', 'Leonardo DiCaprioEmily MortimerMark Ruffalo', 'Jeff BridgesJohn GoodmanJulianne Moore', 'Marlon BrandoMaria SchneiderMaria Michi', 'Matt DamonGwyneth PaltrowJude Law', 'Sylvester StalloneBrian DennehyRichard Crenna', 'Ewan McGregorPierce BrosnanOlivia Williams', 'Hilary SwankClint EastwoodMorgan Freeman', 'Billy Bob ThorntonFrances McDormandMichael Badalucco', 'Mickey RourkeMarisa TomeiEvan Rachel Wood', 'Michael CaineEmily MortimerDavid Bradley', 'Franka PotenteMatt DamonChris Cooper', 'Ugo TognazziMichel SerraultClaire Maurier', 'Daniel Day-LewisPaul DanoCiarán Hinds', 'Jamie BellJulie WaltersJean Heywood', 'Steve CarellToni ColletteGreg Kinnear', 'Ian McKellenMartin FreemanRichard Armitage', 'Jennifer LawrenceJosh HutchersonLiam Hemsworth', 'Anthony PerkinsJanet LeighVera Miles', 'Henry ThomasDrew BarrymorePeter Coyote', 'Dustin HoffmanMeryl StreepJane Alexander', 'Diane LaneRaoul BovaSandra Oh', 'Felicity HuffmanKevin ZegersFionnula Flanagan', 'Ben BurttElissa KnightJeff Garlin', 'Clint EastwoodAndrew RobinsonHarry Guardino', 'Hayden ChristensenNatalie PortmanEwan McGregor', 'Wil WheatonRiver PhoenixCorey Feldman', 'Heather LangenkampJohnny DeppRobert Englund', 'Albert BrooksEllen DeGeneresAlexander Gould', 'Sam NeillJürgen ProchnowJulie Carmen', 'Bruce WillisMilla JovovichGary Oldman', 'Bruce WillisHaley Joel OsmentToni Collette', 'Emilio EchevarríaGael García BernalGoya Toledo', 'Sam NeillLaura DernJeff Goldblum', 'Al PacinoSean PennPenelope Ann Miller', 'Bruce CampbellEmbeth DavidtzMarcus Gilbert', 'John CleeseJamie Lee CurtisKevin Kline', 'Robin WilliamsMatt DamonBen Affleck', 'Elizabeth TaylorPaul NewmanBurl Ives', 'Arnold SchwarzeneggerSharon StoneMichael Ironside', 'Chow Yun-FatMichelle YeohZiyi Zhang', 'Alexandra DahlströmRebecka LiljebergErica Carlson', 'Sean PennBenicio Del ToroNaomi Watts', 'Robert De NiroNick NolteJessica Lange', 'Denzel WashingtonClive OwenJodie Foster', 'Mickey RourkeJessica AlbaJosh Brolin', 'Bill MurrayAndie MacDowellChris Elliott', 'Kevin CostnerGary OldmanJack Lemmon', 'Josh HartnettEwan McGregorTom Sizemore', 'Gael García BernalFele MartínezJavier Cámara', 'Jackie Earle HaleyPatrick WilsonCarla Gugino', 'Robert GustafssonIwar WiklanderDavid Wiberg', 'Oksana AkinshinaArtyom BogucharskiyPavel Ponomaryov', 'Javier BardemBelén RuedaLola Dueñas', 'Leonardo DiCaprioTom HanksChristopher Walken', 'Jim CarreyDanny DeVitoGerry Becker', 'Ethan HawkeVincent SpanoJosh Hamilton', 'Robert RedfordBrad PittCatherine McCormack', 'Angelina JolieColm FeoreAmy Ryan', 'Kate WinsletRalph FiennesBruno Ganz', 'Arnold SchwarzeneggerCarl WeathersKevin Peter Hall', 'Gene HackmanRebecca PidgeonDanny DeVito', 'Jason StathamSaffron BurrowsStephen Campbell Moore', 'Isabella RosselliniKyle MacLachlanDennis Hopper', 'John CusackIben HjejleTodd Louiso', 'Brad PittCate BlanchettTilda Swinton', 'Ralph FiennesJuliette BinocheWillem Dafoe', 'Judy GarlandFrank MorganRay Bolger', 'Cary GrantKatharine HepburnJames Stewart', 'John WayneDean MartinRicky Nelson', 'Gérard JugnotFrançois BerléandJean-Baptiste Maunier', 'Nicolas CageEthan HawkeJared Leto', 'Jason FlemyngDexter FletcherNick Moran', 'Ewan McGregorAlbert FinneyBilly Crudup', 'Timothy BalmeDiana PeñalverElizabeth Moody'] 250

In [43]:
a=[]
for movie in soup.find_all('span',class_='sc-5179a348-7 idrYgr dli-title-metadata-item'):
    a.append(movie.text)

In [44]:
print(a,end='')
print(len(a))

['1972', '2h 55m', 'R', '1991', '1h 58m', 'R', '1980', '2h 4m', 'PG', '1994', '2h 22m', 'R', '1980', '2h 26m', 'R', '1942', '1h 42m', 'PG', '1975', '2h 13m', 'R', '1981', '1h 55m', 'PG', '2003', '3h 21m', 'PG-13', '1977', '2h 1m', 'PG', '2008', '2h 32m', 'PG-13', '1974', '3h 22m', 'R', '1986', '2h 17m', 'R', '1993', '3h 15m', 'R', '2010', '2h 28m', 'PG-13', '2001', '2h 58m', 'PG-13', '1979', '1h 57m', 'R', '1959', '2h 1m', 'Approved', '1982', '1h 57m', 'R', '1995', '2h 7m', 'R', '1979', '2h 27m', 'R', '1957', '1h 36m', 'Approved', '2002', '2h 59m', 'PG-13', '1991', '2h 17m', 'R', '1983', '2h 11m', 'PG', '1988', '2h 12m', 'R', '1939', '3h 58m', 'G', '1976', '1h 54m', 'R', '1994', '2h 34m', 'R', '1957', '2h 41m', 'PG', '1994', '1h 28m', 'G', '1959', '2h 16m', 'Approved', '1954', '1h 52m', 'PG', '1994', '1h 50m', 'R', '1985', '1h 56m', 'PG', '1941', '1h 59m', 'PG', '1990', '2h 25m', 'R', '2000', '1h 53m', 'R', '1999', '2h 2m', 'R', '1997', '2h 19m', 'PG-13', '1994', '2h 22m', 'PG-13', '1952', '1h 43m', 'G', '1995', '2h 58m', 'R', '1998', '2h 49m', 'R', '1988', '2h 13m', 'R', '2010', '1h 58m', 'R', '1968', '2h 29m', 'G', '2003', '1h 51m', 'R', '1972', '2h 24m', 'R', '1966', '2h 58m', 'R', '2001', '2h 2m', 'R', '1936', '1h 27m', 'G', '2003', '1h 42m', 'R', '1987', '1h 56m', 'R', '2000', '1h 42m', 'NC-17', '1999', '2h 19m', 'R', '2007', '2h 2m', 'R', '2012', '2h 45m', 'R', '2006', '1h 49m', 'R', '2007', '1h 51m', 'G', '2006', '2h 17m', 'R', '2006', '2h 10m', 'PG-13', '2005', '2h 12m', 'R', '1974', '2h 10m', 'R', '2002', '2h 10m', 'R', '1944', '1h 40m', 'Approved', '1996', '1h 38m', 'R', '2012', '2h 7m', 'PG', '2008', '2h', 'R', '1958', '2h 8m', 'PG', '1996', '1h 33m', 'R', '2014', '2h 49m', 'PG-13', '1982', '1h 49m', 'R', '1949', '1h 44m', 'Approved', '1995', '2h 9m', 'R', '1997', '1h 56m', 'PG-13', '2002', '2h 30m', 'R', '1999', '3h 8m', 'R', '2012', '2h 44m', 'PG-13', '2015', '2h 18m', 'PG-13', '2013', '2h 41m', 'PG-13', '2015', '2h', 'R', '2013', '2h 14m', 'R', '1989', '2h 7m', 'PG-13', '2000', '1h 47m', 'PG-13', '2009', '2h 33m', 'R', '2006', '2h 31m', 'R', '2001', '2h 15m', 'PG-13', '2009', '1h 52m', 'R', '1993', '2h 1m', 'R', '2003', '2h 18m', 'R', '1999', '2h 37m', 'R', '1997', '2h 18m', 'R', '1995', '2h 50m', 'R', '1995', '1h 46m', 'R', '1967', '2h 7m', 'Approved', '2004', '1h 48m', 'R', '1931', '1h 27m', 'G', '1999', '2h 16m', 'R', '2005', '2h 4m', 'R', '1990', '1h 47m', 'R', '1993', '1h 58m', 'PG-13', '1975', '1h 31m', 'PG', '1978', '3h 3m', 'R', '1983', '2h 50m', 'R', '1971', '2h 16m', 'R', '1980', '2h 4m', 'PG', '1973', '2h 31m', 'R', '1962', '3h 47m', 'PG', '1955', '1h 58m', 'PG', '2004', '2h 1m', 'PG-13', '1990', '3h 1m', 'PG-13', '2003', '2h 23m', 'PG-13', '2005', '2h 20m', 'PG-13', '2012', '2h 23m', 'PG-13', '1948', '2h 6m', 'Approved', '1987', '1h 59m', 'R', '1998', '1h 43m', 'PG', '1992', '1h 39m', 'R', '1960', '2h 5m', 'Approved', '1946', '1h 54m', 'Approved', '2012', '2h 7m', 'PG-13', '2014', '1h 42m', 'Not Rated', '1959', '3h 32m', 'G', '1998', '2h 14m', 'NC-17', '1963', '2h 18m', 'Not Rated', '1991', '2h 10m', 'R', '2004', '2h 36m', 'R', '1976', '2h', 'PG', '2008', '1h 56m', 'R', '1951', '1h 41m', 'PG', '1966', '2h 11m', 'Approved', '1973', '2h 2m', 'R', '1984', '1h 47m', 'R', '2012', '2h 49m', 'PG-13', '2004', '2h 17m', 'R', '2000', '2h 35m', 'R', '2000', '2h 27m', 'R', '2007', '2h 37m', 'R', '1999', '3h 9m', 'R', '2009', '2h 42m', 'PG-13', '1978', '1h 31m', 'R', '1995', '2h 58m', 'R', '1975', '2h 4m', 'PG', '1968', '2h 46m', 'PG-13', '1946', '1h 42m', 'Approved', '1963', '2h 52m', 'Approved', '1993', '1h 16m', 'PG', '1964', '1h 50m', 'Approved', '2007', '2h 7m', 'R', '2012', '2h', 'R', '2008', '2h 8m', 'R', '1999', '1h 53m', 'R', '2010', '1h 48m', 'R', '2001', '1h 44m', 'PG-13', '2005', '2h 14m', 'R', '2004', '2h', 'R', '1997', '2h 34m', 'R', '2006', '2h 24m', 'PG-13', '1986', '2h', 'R', '1998', '2h 50m', 'R', '2013', '2h 26m', 'PG-13', '1990', '2h 42m', 'R', '1998', '1h 59m', 'R', '1989', '2h 8m', 'PG', '2007', '1h 44m', 'PG-13', '2002', '1h 52m', 'R', '2009', '2h 32m', 'R', '1981', '2h 29m', '2004', '2h 7m', 'R', '1992', '2h 36m', 'R', '1972', '1h 49m', 'R', '2008', '1h 30m', 'PG-13', '1989', '1h 48m', 'PG', '1957', '1h 21m', 'Approved', '1993', '2h 10m', 'PG-13', '2010', '2h 18m', 'R', '1998', '1h 57m', 'R', '1972', '2h 9m', 'NC-17', '1999', '2h 19m', 'R', '1982', '1h 33m', 'R', '2010', '2h 8m', 'PG-13', '2004', '2h 12m', 'PG-13', '2001', '1h 56m', 'R', '2008', '1h 49m', 'R', '2009', '1h 43m', 'R', '2002', '1h 59m', 'PG-13', '1978', '1h 37m', 'R', '2007', '2h 38m', 'R', '2000', '1h 50m', 'R', '2006', '1h 41m', 'R', '2014', '2h 24m', 'R', '2012', '2h 22m', 'PG-13', '1960', '1h 49m', 'R', '1982', '1h 55m', 'PG', '1979', '1h 45m', 'PG', '2003', '1h 53m', 'PG-13', '2005', '1h 43m', 'R', '2008', '1h 38m', 'G', '1971', '1h 42m', 'R', '2005', '2h 20m', 'PG-13', '1986', '1h 29m', 'R', '1984', '1h 31m', 'R', '2003', '1h 40m', 'G', '1994', '1h 35m', 'R', '1997', '2h 6m', 'PG-13', '1999', '1h 47m', 'PG-13', '2000', '2h 34m', 'R', '1993', '2h 7m', 'PG-13', '1993', '2h 24m', 'R', '1992', '1h 21m', 'R', '1988', '1h 48m', 'R', '1997', '2h 6m', 'R', '1958', '1h 48m', 'Approved', '1990', '1h 53m', 'R', '2000', '2h', 'PG-13', '1998', '1h 29m', 'Not Rated', '2003', '2h 4m', 'R', '1991', '2h 8m', 'R', '2006', '2h 9m', 'R', '2014', '1h 42m', 'R', '1993', '1h 41m', 'PG', '1991', '3h 9m', 'R', '2001', '2h 24m', 'R', '2004', '1h 46m', 'R', '2009', '2h 42m', 'R', '2013', '1h 54m', 'R', '2002', '1h 49m', 'R', '2004', '2h 6m', 'PG-13', '2002', '2h 21m', 'PG-13', '1999', '1h 58m', 'R', '1993', '2h 8m', 'R', '2001', '2h 6m', 'R', '2008', '2h 21m', 'R', '2008', '2h 4m', 'R', '1987', '1h 47m', 'R', '2001', '1h 49m', 'R', '2008', '1h 51m', 'R', '1986', '2h', 'R', '2000', '1h 53m', 'R', '2008', '2h 46m', 'PG-13', '1996', '2h 42m', 'R', '1939', '1h 42m', 'G', '1940', '1h 52m', 'Approved', '1959', '2h 21m', 'Approved', '2004', '1h 37m', 'PG-13', '2005', '2h 2m', 'R', '1998', '1h 47m', 'R', '2003', '2h 5m', 'PG-13', '1992', '1h 44m', 'R']749

In [45]:
a ="'1972', '2h 55m', 'R', '1991', '1h 58m', 'R', '1980', '2h 4m', 'PG', '1994', '2h 22m', 'R', '1980', '2h 26m', 'R', '1942', '1h 42m', 'PG', '1975', '2h 13m', 'R', '1981', '1h 55m', 'PG', '2003', '3h 21m', 'PG-13', '1977', '2h 1m', 'PG', '2008', '2h 32m', 'PG-13', '1974', '3h 22m', 'R', '1986', '2h 17m', 'R', '1993', '3h 15m', 'R', '2010', '2h 28m', 'PG-13', '2001', '2h 58m', 'PG-13', '1979', '1h 57m', 'R', '1959', '2h 1m', 'Approved', '1982', '1h 57m', 'R', '1995', '2h 7m', 'R', '1979', '2h 27m', 'R', '1957', '1h 36m', 'Approved', '2002', '2h 59m', 'PG-13', '1991', '2h 17m', 'R', '1983', '2h 11m', 'PG', '1988', '2h 12m', 'R', '1939', '3h 58m', 'G', '1976', '1h 54m', 'R', '1994', '2h 34m', 'R', '1957', '2h 41m', 'PG', '1994', '1h 28m', 'G', '1959', '2h 16m', 'Approved', '1954', '1h 52m', 'PG', '1994', '1h 50m', 'R', '1985', '1h 56m', 'PG', '1941', '1h 59m', 'PG', '1990', '2h 25m', 'R', '2000', '1h 53m', 'R', '1999', '2h 2m', 'R', '1997', '2h 19m', 'PG-13', '1994', '2h 22m', 'PG-13', '1952', '1h 43m', 'G', '1995', '2h 58m', 'R', '1998', '2h 49m', 'R', '1988', '2h 13m', 'R', '2010', '1h 58m', 'R', '1968', '2h 29m', 'G', '2003', '1h 51m', 'R', '1972', '2h 24m', 'R', '1966', '2h 58m', 'R', '2001', '2h 2m', 'R', '1936', '1h 27m', 'G', '2003', '1h 42m', 'R', '1987', '1h 56m', 'R', '2000', '1h 42m', 'NC-17', '1999', '2h 19m', 'R', '2007', '2h 2m', 'R', '2012', '2h 45m', 'R', '2006', '1h 49m', 'R', '2007', '1h 51m', 'G', '2006', '2h 17m', 'R', '2006', '2h 10m', 'PG-13', '2005', '2h 12m', 'R', '1974', '2h 10m', 'R', '2002', '2h 10m', 'R', '1944', '1h 40m', 'Approved', '1996', '1h 38m', 'R', '2012', '2h 7m', 'PG', '2008', '2h', 'R', '1958', '2h 8m', 'PG', '1996', '1h 33m', 'R', '2014', '2h 49m', 'PG-13', '1982', '1h 49m', 'R', '1949', '1h 44m', 'Approved', '1995', '2h 9m', 'R', '1997', '1h 56m', 'PG-13', '2002', '2h 30m', 'R', '1999', '3h 8m', 'R', '2012', '2h 44m', 'PG-13', '2015', '2h 18m', 'PG-13', '2013', '2h 41m', 'PG-13', '2015', '2h', 'R', '2013', '2h 14m', 'R', '1989', '2h 7m', 'PG-13', '2000', '1h 47m', 'PG-13', '2009', '2h 33m', 'R', '2006', '2h 31m', 'R', '2001', '2h 15m', 'PG-13', '2009', '1h 52m', 'R', '1993', '2h 1m', 'R', '2003', '2h 18m', 'R', '1999', '2h 37m', 'R', '1997', '2h 18m', 'R', '1995', '2h 50m', 'R', '1995', '1h 46m', 'R', '1967', '2h 7m', 'Approved', '2004', '1h 48m', 'R', '1931', '1h 27m', 'G', '1999', '2h 16m', 'R', '2005', '2h 4m', 'R', '1990', '1h 47m', 'R', '1993', '1h 58m', 'PG-13', '1975', '1h 31m', 'PG', '1978', '3h 3m', 'R', '1983', '2h 50m', 'R', '1971', '2h 16m', 'R', '1980', '2h 4m', 'PG', '1973', '2h 31m', 'R', '1962', '3h 47m', 'PG', '1955', '1h 58m', 'PG', '2004', '2h 1m', 'PG-13', '1990', '3h 1m', 'PG-13', '2003', '2h 23m', 'PG-13', '2005', '2h 20m', 'PG-13', '2012', '2h 23m', 'PG-13', '1948', '2h 6m', 'Approved', '1987', '1h 59m', 'R', '1998', '1h 43m', 'PG', '1992', '1h 39m', 'R', '1960', '2h 5m', 'Approved', '1946', '1h 54m', 'Approved', '2012', '2h 7m', 'PG-13', '2014', '1h 42m', 'Not Rated', '1959', '3h 32m', 'G', '1998', '2h 14m', 'NC-17', '1963', '2h 18m', 'Not Rated', '1991', '2h 10m', 'R', '2004', '2h 36m', 'R', '1976', '2h', 'PG', '2008', '1h 56m', 'R', '1951', '1h 41m', 'PG', '1966', '2h 11m', 'Approved', '1973', '2h 2m', 'R', '1984', '1h 47m', 'R', '2012', '2h 49m', 'PG-13', '2004', '2h 17m', 'R', '2000', '2h 35m', 'R', '2000', '2h 27m', 'R', '2007', '2h 37m', 'R', '1999', '3h 9m', 'R', '2009', '2h 42m', 'PG-13', '1978', '1h 31m', 'R', '1995', '2h 58m', 'R', '1975', '2h 4m', 'PG', '1968', '2h 46m', 'PG-13', '1946', '1h 42m', 'Approved', '1963', '2h 52m', 'Approved', '1993', '1h 16m', 'PG', '1964', '1h 50m', 'Approved', '2007', '2h 7m', 'R', '2012', '2h', 'R', '2008', '2h 8m', 'R', '1999', '1h 53m', 'R', '2010', '1h 48m', 'R', '2001', '1h 44m', 'PG-13', '2005', '2h 14m', 'R', '2004', '2h', 'R', '1997', '2h 34m', 'R', '2006', '2h 24m', 'PG-13', '1986', '2h', 'R', '1998', '2h 50m', 'R', '2013', '2h 26m', 'PG-13', '1990', '2h 42m', 'R', '1998', '1h 59m', 'R', '1989', '2h 8m', 'PG', '2007', '1h 44m', 'PG-13', '2002', '1h 52m', 'R', '2009', '2h 32m', 'R', '1981', '2h 29m', '2004', '2h 7m', 'R', '1992', '2h 36m', 'R', '1972', '1h 49m', 'R', '2008', '1h 30m', 'PG-13', '1989', '1h 48m', 'PG', '1957', '1h 21m', 'Approved', '1993', '2h 10m', 'PG-13', '2010', '2h 18m', 'R', '1998', '1h 57m', 'R', '1972', '2h 9m', 'NC-17', '1999', '2h 19m', 'R', '1982', '1h 33m', 'R', '2010', '2h 8m', 'PG-13', '2004', '2h 12m', 'PG-13', '2001', '1h 56m', 'R', '2008', '1h 49m', 'R', '2009', '1h 43m', 'R', '2002', '1h 59m', 'PG-13', '1978', '1h 37m', 'R', '2007', '2h 38m', 'R', '2000', '1h 50m', 'R', '2006', '1h 41m', 'R', '2014', '2h 24m', 'R', '2012', '2h 22m', 'PG-13', '1960', '1h 49m', 'R', '1982', '1h 55m', 'PG', '1979', '1h 45m', 'PG', '2003', '1h 53m', 'PG-13', '2005', '1h 43m', 'R', '2008', '1h 38m', 'G', '1971', '1h 42m', 'R', '2005', '2h 20m', 'PG-13', '1986', '1h 29m', 'R', '1984', '1h 31m', 'R', '2003', '1h 40m', 'G', '1994', '1h 35m', 'R', '1997', '2h 6m', 'PG-13', '1999', '1h 47m', 'PG-13', '2000', '2h 34m', 'R', '1993', '2h 7m', 'PG-13', '1993', '2h 24m', 'R', '1992', '1h 21m', 'R', '1988', '1h 48m', 'R', '1997', '2h 6m', 'R', '1958', '1h 48m', 'Approved', '1990', '1h 53m', 'R', '2000', '2h', 'PG-13', '1998', '1h 29m', 'Not Rated', '2003', '2h 4m', 'R', '1991', '2h 8m', 'R', '2006', '2h 9m', 'R', '2014', '1h 42m', 'R', '1993', '1h 41m', 'PG', '1991', '3h 9m', 'R', '2001', '2h 24m', 'R', '2004', '1h 46m', 'R', '2009', '2h 42m', 'R', '2013', '1h 54m', 'R', '2002', '1h 49m', 'R', '2004', '2h 6m', 'PG-13', '2002', '2h 21m', 'PG-13', '1999', '1h 58m', 'R', '1993', '2h 8m', 'R', '2001', '2h 6m', 'R', '2008', '2h 21m', 'R', '2008', '2h 4m', 'R', '1987', '1h 47m', 'R', '2001', '1h 49m', 'R', '2008', '1h 51m', 'R', '1986', '2h', 'R', '2000', '1h 53m', 'R', '2008', '2h 46m', 'PG-13', '1996', '2h 42m', 'R', '1939', '1h 42m', 'G', '1940', '1h 52m', 'Approved', '1959', '2h 21m', 'Approved', '2004', '1h 37m', 'PG-13', '2005', '2h 2m', 'R', '1998', '1h 47m', 'R', '2003', '2h 5m', 'PG-13', '1992', '1h 44m', 'R'"
b=re.findall("'([A-Za-z-]+)'|'([A-Za-z]+\-\d+)|'([a-zA-Z]+\s[a-zA-Z]+)'",a)

<>:2: SyntaxWarning: invalid escape sequence '\-'
<>:2: SyntaxWarning: invalid escape sequence '\-'
C:\Users\Dhiraj Rathod\AppData\Local\Temp\ipykernel_10916\2448513267.py:2: SyntaxWarning: invalid escape sequence '\-'
  b=re.findall("'([A-Za-z-]+)'|'([A-Za-z]+\-\d+)|'([a-zA-Z]+\s[a-zA-Z]+)'",a)

In [46]:
print(b,len(b))

[('R', '', ''), ('R', '', ''), ('PG', '', ''), ('R', '', ''), ('R', '', ''), ('PG', '', ''), ('R', '', ''), ('PG', '', ''), ('', 'PG-13', ''), ('PG', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('R', '', ''), ('Approved', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('Approved', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('PG', '', ''), ('R', '', ''), ('G', '', ''), ('R', '', ''), ('R', '', ''), ('PG', '', ''), ('G', '', ''), ('Approved', '', ''), ('PG', '', ''), ('R', '', ''), ('PG', '', ''), ('PG', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('G', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('G', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('G', '', ''), ('R', '', ''), ('R', '', ''), ('', 'NC-17', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('G', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('Approved', '', ''), ('R', '', ''), ('PG', '', ''), ('R', '', ''), ('PG', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('Approved', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('Approved', '', ''), ('R', '', ''), ('G', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('PG', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('PG', '', ''), ('R', '', ''), ('PG', '', ''), ('PG', '', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('Approved', '', ''), ('R', '', ''), ('PG', '', ''), ('R', '', ''), ('Approved', '', ''), ('Approved', '', ''), ('', 'PG-13', ''), ('', '', 'Not Rated'), ('G', '', ''), ('', 'NC-17', ''), ('', '', 'Not Rated'), ('R', '', ''), ('R', '', ''), ('PG', '', ''), ('R', '', ''), ('PG', '', ''), ('Approved', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('PG', '', ''), ('', 'PG-13', ''), ('Approved', '', ''), ('Approved', '', ''), ('PG', '', ''), ('Approved', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('PG', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('PG', '', ''), ('Approved', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('', 'NC-17', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('PG', '', ''), ('PG', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('G', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('G', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('Approved', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('', '', 'Not Rated'), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('PG', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('G', '', ''), ('Approved', '', ''), ('Approved', '', ''), ('', 'PG-13', ''), ('R', '', ''), ('R', '', ''), ('', 'PG-13', ''), ('R', '', '')] 249

In [47]:
movie_type = []

In [48]:
for i in b:
    for j in i:
        if j=='':
            pass
        else:
            movie_type.append(j)

In [49]:
print(movie_type,len(movie_type))

['R', 'R', 'PG', 'R', 'R', 'PG', 'R', 'PG', 'PG-13', 'PG', 'PG-13', 'R', 'R', 'R', 'PG-13', 'PG-13', 'R', 'Approved', 'R', 'R', 'R', 'Approved', 'PG-13', 'R', 'PG', 'R', 'G', 'R', 'R', 'PG', 'G', 'Approved', 'PG', 'R', 'PG', 'PG', 'R', 'R', 'R', 'PG-13', 'PG-13', 'G', 'R', 'R', 'R', 'R', 'G', 'R', 'R', 'R', 'R', 'G', 'R', 'R', 'NC-17', 'R', 'R', 'R', 'R', 'G', 'R', 'PG-13', 'R', 'R', 'R', 'Approved', 'R', 'PG', 'R', 'PG', 'R', 'PG-13', 'R', 'Approved', 'R', 'PG-13', 'R', 'R', 'PG-13', 'PG-13', 'PG-13', 'R', 'R', 'PG-13', 'PG-13', 'R', 'R', 'PG-13', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'Approved', 'R', 'G', 'R', 'R', 'R', 'PG-13', 'PG', 'R', 'R', 'R', 'PG', 'R', 'PG', 'PG', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'Approved', 'R', 'PG', 'R', 'Approved', 'Approved', 'PG-13', 'Not Rated', 'G', 'NC-17', 'Not Rated', 'R', 'R', 'PG', 'R', 'PG', 'Approved', 'R', 'R', 'PG-13', 'R', 'R', 'R', 'R', 'R', 'PG-13', 'R', 'R', 'PG', 'PG-13', 'Approved', 'Approved', 'PG', 'Approved', 'R', 'R', 'R', 'R', 'R', 'PG-13', 'R', 'R', 'R', 'PG-13', 'R', 'R', 'PG-13', 'R', 'R', 'PG', 'PG-13', 'R', 'R', 'R', 'R', 'R', 'PG-13', 'PG', 'Approved', 'PG-13', 'R', 'R', 'NC-17', 'R', 'R', 'PG-13', 'PG-13', 'R', 'R', 'R', 'PG-13', 'R', 'R', 'R', 'R', 'R', 'PG-13', 'R', 'PG', 'PG', 'PG-13', 'R', 'G', 'R', 'PG-13', 'R', 'R', 'G', 'R', 'PG-13', 'PG-13', 'R', 'PG-13', 'R', 'R', 'R', 'R', 'Approved', 'R', 'PG-13', 'Not Rated', 'R', 'R', 'R', 'R', 'PG', 'R', 'R', 'R', 'R', 'R', 'R', 'PG-13', 'PG-13', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'PG-13', 'R', 'G', 'Approved', 'Approved', 'PG-13', 'R', 'R', 'PG-13', 'R'] 249

In [50]:
for i in range(len(movie_type)):
    if i == 169:
        movie_type.insert(i,np.nan)

In [51]:
print(movie_type,len(movie_type))

['R', 'R', 'PG', 'R', 'R', 'PG', 'R', 'PG', 'PG-13', 'PG', 'PG-13', 'R', 'R', 'R', 'PG-13', 'PG-13', 'R', 'Approved', 'R', 'R', 'R', 'Approved', 'PG-13', 'R', 'PG', 'R', 'G', 'R', 'R', 'PG', 'G', 'Approved', 'PG', 'R', 'PG', 'PG', 'R', 'R', 'R', 'PG-13', 'PG-13', 'G', 'R', 'R', 'R', 'R', 'G', 'R', 'R', 'R', 'R', 'G', 'R', 'R', 'NC-17', 'R', 'R', 'R', 'R', 'G', 'R', 'PG-13', 'R', 'R', 'R', 'Approved', 'R', 'PG', 'R', 'PG', 'R', 'PG-13', 'R', 'Approved', 'R', 'PG-13', 'R', 'R', 'PG-13', 'PG-13', 'PG-13', 'R', 'R', 'PG-13', 'PG-13', 'R', 'R', 'PG-13', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'Approved', 'R', 'G', 'R', 'R', 'R', 'PG-13', 'PG', 'R', 'R', 'R', 'PG', 'R', 'PG', 'PG', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'Approved', 'R', 'PG', 'R', 'Approved', 'Approved', 'PG-13', 'Not Rated', 'G', 'NC-17', 'Not Rated', 'R', 'R', 'PG', 'R', 'PG', 'Approved', 'R', 'R', 'PG-13', 'R', 'R', 'R', 'R', 'R', 'PG-13', 'R', 'R', 'PG', 'PG-13', 'Approved', 'Approved', 'PG', 'Approved', 'R', 'R', 'R', 'R', 'R', 'PG-13', 'R', 'R', 'R', 'PG-13', 'R', 'R', 'PG-13', 'R', 'R', 'PG', 'PG-13', 'R', 'R', 'R', nan, 'R', 'R', 'PG-13', 'PG', 'Approved', 'PG-13', 'R', 'R', 'NC-17', 'R', 'R', 'PG-13', 'PG-13', 'R', 'R', 'R', 'PG-13', 'R', 'R', 'R', 'R', 'R', 'PG-13', 'R', 'PG', 'PG', 'PG-13', 'R', 'G', 'R', 'PG-13', 'R', 'R', 'G', 'R', 'PG-13', 'PG-13', 'R', 'PG-13', 'R', 'R', 'R', 'R', 'Approved', 'R', 'PG-13', 'Not Rated', 'R', 'R', 'R', 'R', 'PG', 'R', 'R', 'R', 'R', 'R', 'R', 'PG-13', 'PG-13', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'PG-13', 'R', 'G', 'Approved', 'Approved', 'PG-13', 'R', 'R', 'PG-13', 'R'] 250

In [70]:
Dict = {'Movie_name':Name,'Release_Year':Year,
       'Time_duration':Time,'Imdb_Rating':Rating,
       'Imdb_votes':Imdb_votes,'Meta_score':metascore,'movie_type':movie_type,'Director':Movie_director,'Actors':Movie_actors,'Movie_Description':Description}
df=pd.DataFrame(Dict)

In [72]:
df.head()

,Movie_name,Release_Year,Time_duration,Imdb_Rating,Imdb_votes,Meta_score,movie_type,Director,Actors,Movie_Description
0,1. The Godfather,1972,2h 55m,9.2,2.1M,100,R,Francis Ford Coppola,Marlon BrandoAl PacinoJames Caan,The aging patriarch of an organized crime dyna...
1,2. The Silence of the Lambs,1991,1h 58m,8.6,1.6M,86,R,Jonathan Demme,Jodie FosterAnthony HopkinsScott Glenn,A young F.B.I. cadet must receive the help of ...
2,3. Star Wars: Episode V - The Empire Strikes Back,1980,2h 4m,8.7,1.4M,82,PG,Irvin Kershner,Mark HamillHarrison FordCarrie Fisher,After the Empire overpowers the Rebel Alliance...
3,4. The Shawshank Redemption,1994,2h 22m,9.3,3M,82,R,Frank Darabont,Tim RobbinsMorgan FreemanBob Gunton,A banker convicted of uxoricide forms a friend...
4,5. The Shining,1980,2h 26m,8.4,1.2M,68,R,Stanley Kubrick,Jack NicholsonShelley DuvallDanny Lloyd,A family heads to an isolated hotel for the wi...

df.info()

In [54]:
df['Release_Year']=df.Release_Year.apply(lambda x : int(x))

In [55]:
df['Imdb_Rating'] = df.Imdb_Rating.apply(lambda x : float(x))

In [56]:
df['Movie_name']=df['Movie_name'].apply(lambda x : x.split('.')[1])

In [57]:
votes=[]
for i in df['Imdb_votes']:
    if 'M' in i:
        votes.append(float(i.replace('M',''))*1000000)
    elif 'K' in i:
        votes.append(float(i.replace('K',''))*1000)
#print(votes,len(votes))

In [58]:
df['Imdb_votes']=votes

In [59]:
df['Meta_score']=df['Meta_score'].apply(lambda x : float(x))

In [60]:
df.fillna({'Meta_score':round(df.Meta_score.mean(),2)},inplace=True)

In [61]:
df

,Movie_name,Release_Year,Time_duration,Imdb_Rating,Imdb_votes,Meta_score,movie_type,Director,Actors,Movie_Description
0,The Godfather,1972,2h 55m,9.2,2100000.0,100.0,R,Francis Ford Coppola,Marlon BrandoAl PacinoJames Caan,The aging patriarch of an organized crime dyna...
1,The Silence of the Lambs,1991,1h 58m,8.6,1600000.0,86.0,R,Jonathan Demme,Jodie FosterAnthony HopkinsScott Glenn,A young F.B.I. cadet must receive the help of ...
2,Star Wars: Episode V - The Empire Strikes Back,1980,2h 4m,8.7,1400000.0,82.0,PG,Irvin Kershner,Mark HamillHarrison FordCarrie Fisher,After the Empire overpowers the Rebel Alliance...
3,The Shawshank Redemption,1994,2h 22m,9.3,3000000.0,82.0,R,Frank Darabont,Tim RobbinsMorgan FreemanBob Gunton,A banker convicted of uxoricide forms a friend...
4,The Shining,1980,2h 26m,8.4,1200000.0,68.0,R,Stanley Kubrick,Jack NicholsonShelley DuvallDanny Lloyd,A family heads to an isolated hotel for the wi...
...,...,...,...,...,...,...,...,...,...,...
245,The Chorus,2004,1h 37m,7.8,69000.0,56.0,PG-13,Christophe Barratier,Gérard JugnotFrançois BerléandJean-Baptiste Ma...,"Pierre, a successful orchestra conductor, retu..."
246,Lord of War,2005,2h 2m,7.6,349000.0,62.0,R,Andrew Niccol,Nicolas CageEthan HawkeJared Leto,An arms dealer confronts the morality of his w...
247,"Lock, Stock and Two Smoking Barrels",1998,1h 47m,8.1,634000.0,67.0,R,Guy Ritchie,Jason FlemyngDexter FletcherNick Moran,When four small-time criminals lose a rigged p...
248,Big Fish,2003,2h 5m,8.0,469000.0,58.0,PG-13,Tim Burton,Ewan McGregorAlbert FinneyBilly Crudup,A frustrated son tries to determine the fact f...
249,Dead Alive,1992,1h 44m,7.5,107000.0,54.0,R,Peter Jackson,Timothy BalmeDiana PeñalverElizabeth Moody,A young man's mother is bitten by a Sumatran r...

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Movie_name         250 non-null    object
 1   Release_Year       250 non-null    int64
 2   Time_duration      250 non-null    object
 3   Imdb_Rating        250 non-null    float64
 4   Imdb_votes         250 non-null    float64
 5   Meta_score         250 non-null    float64
 6   movie_type         249 non-null    object
 7   Director           250 non-null    object
 8   Actors             250 non-null    object
 9   Movie_Description  250 non-null    object
dtypes: float64(3), int64(1), object(6)
memory usage: 19.7+ KB

In [67]:
df.head()

,Movie_name,Release_Year,Time_duration,Imdb_Rating,Imdb_votes,Meta_score,movie_type,Director,Actors,Movie_Description
0,The Godfather,1972,2h 55m,9.2,2100000.0,100.0,R,Francis Ford Coppola,Marlon BrandoAl PacinoJames Caan,The aging patriarch of an organized crime dyna...
1,The Silence of the Lambs,1991,1h 58m,8.6,1600000.0,86.0,R,Jonathan Demme,Jodie FosterAnthony HopkinsScott Glenn,A young F.B.I. cadet must receive the help of ...
2,Star Wars: Episode V - The Empire Strikes Back,1980,2h 4m,8.7,1400000.0,82.0,PG,Irvin Kershner,Mark HamillHarrison FordCarrie Fisher,After the Empire overpowers the Rebel Alliance...
3,The Shawshank Redemption,1994,2h 22m,9.3,3000000.0,82.0,R,Frank Darabont,Tim RobbinsMorgan FreemanBob Gunton,A banker convicted of uxoricide forms a friend...
4,The Shining,1980,2h 26m,8.4,1200000.0,68.0,R,Stanley Kubrick,Jack NicholsonShelley DuvallDanny Lloyd,A family heads to an isolated hotel for the wi...

In [63]:
#df.to_csv('df1.csv',index=False)